#### 主要讲一下 Tensor 格式的一些数据类型

1. tensor 不同维度的几种应用  
    **1.1 0维常用于 loss 计算 value**  
    **1.2 1维 用于 bias，linear_input 等加减法或输入 [value]**  
    **1.3 2维 用于多个linear_input 的计算 [b, value]**   
    **1.4 3维 用于 NLP等RNN网络处理 [b, n_word, feat]**  
    **1.5 4维 用于 图片等CNN网络处理 [b, c, w, h]**  
2. 常用的数据类型、常用的几个属性和函数、创建tensor  
3. 有趣的生成函数

In [1]:
import torch

#### 常用的数据类型
torch.float32 / 64   
torch.int8 /16 / 32 / 64  
torch.long  
torch.uint8    

#### 常用的几个属性和函数
tensor.shape  # tensor的尺寸 等同于tensor.size()  
tensor.numel()  # number of element 参数大小   
tensor.dim()  # 维度数  
tensor.type() # tensor 类型

In [4]:
# 输入一个数值，返回一个 0维的tensor
a = torch.tensor(5)
a.shape,a

(torch.Size([]), tensor(5))

#### 创建 tensor
#输入数值或列表  
torch.tensor()  
#指定类型--给的是shape  
torch.FloatTensor()  
torch.IntTensor()  
torch.ByteTensor()
#随机数值--给的是shape  
torch.rand() -- [0,1]间随机取值  
torch.randint(min,max,[shape])-- 区间取值  
torch.randn() --mean=0,std=1正态分布     
#从numpy中读取  
torch.from_numpy()  
#生成相同类型矩阵函数  
torch.*_like（a）

In [14]:
b = torch.randn(2,3,3)
b.dim(),b.size(),b.type(),b

(3,
 torch.Size([2, 3, 3]),
 'torch.FloatTensor',
 tensor([[[-0.2687,  1.0556,  1.3079],
          [ 0.8656,  0.4804,  0.1538],
          [ 0.1244,  1.4243, -1.1985]],
 
         [[-0.0427,  0.5887, -0.6269],
          [ 1.8963, -0.5378, -2.2035],
          [ 0.1506,  0.4445,  0.0195]]]))

In [21]:
c = torch.FloatTensor(2,3,3)
c

tensor([[[2.3694e-38, 2.3694e-38, 2.3694e-38],
         [2.3694e-38, 2.3694e-38, 2.3694e-38],
         [2.3694e-38, 2.3694e-38, 2.3694e-38]],

        [[2.3694e-38, 2.3694e-38, 2.3694e-38],
         [2.3694e-38, 2.3694e-38, 2.3694e-38],
         [2.3694e-38, 2.3694e-38, 2.3694e-38]]])

In [15]:
import numpy as np

In [22]:
d = np.arange(9)
e = torch.from_numpy(d)
d,e

(array([0, 1, 2, 3, 4, 5, 6, 7, 8]),
 tensor([0, 1, 2, 3, 4, 5, 6, 7, 8], dtype=torch.int32))

#### 有趣的生成函数
#填充值  
torch.full([shape],value)  
#函数取值  
torch.linspace(min,max,steps) --线性等分  
torch.logspace(min,max,steps) --log等分  
#对角矩阵
torch.eye() 

In [23]:
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])