### 索引与切片
1. 两个符号 ... 与 :
2. 几个索引函数
3. 条件索引

In [1]:
import torch

In [3]:
a = torch.rand(4,3,10,10)

#### 符号使用
: --一个维度索引，有3种情况  
__ __[:] --全部索引  
__ __[a:], [:b], [c:d] --等值索引  
__ __[a:b:2],[::2] --跨步索引  
... --多个维度全选  
__ __[...,1:4] --前全部维度操作
 

In [5]:
a.shape

torch.Size([4, 3, 10, 10])

In [7]:
a[:,2].shape

torch.Size([4, 10, 10])

In [8]:
a[...,1:4].shape

torch.Size([4, 3, 10, 3])

#### 掩码矩阵索引
mask * a

#### 补充几个逻辑操作
#a是输入矩阵，b可以是数值也可以是矩阵  
#返回值是{0，1}，类型是torch.byte，如果要运算需要转换类型 tensor.to()
torch.eq(a,b) --equal  
torch.ge(a,b) --great or equal  
torch.gt(a,b) --great than   
torch.le(a,b) --little or equal  
torch.lt(a,b) --little than  

In [33]:
mask = torch.gt(a,0.5).to(torch.float)

In [34]:
b = mask*a

In [35]:
b.shape

torch.Size([4, 3, 10, 10])

In [38]:
b[0,0]

tensor([[0.9716, 0.7338, 0.0000, 0.0000, 0.0000, 0.5485, 0.0000, 0.0000, 0.0000,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.6722, 0.5131, 0.5744, 0.0000,
         0.0000],
        [0.9826, 0.8712, 0.0000, 0.7652, 0.0000, 0.9929, 0.9359, 0.5037, 0.0000,
         0.5951],
        [0.6162, 0.5442, 0.5320, 0.6576, 0.6155, 0.0000, 0.0000, 0.0000, 0.5026,
         0.7747],
        [0.0000, 0.5992, 0.0000, 0.7123, 0.0000, 0.0000, 0.0000, 0.8724, 0.0000,
         0.5920],
        [0.6625, 0.5744, 0.5935, 0.9419, 0.8801, 0.6988, 0.9758, 0.0000, 0.5126,
         0.0000],
        [0.0000, 0.6461, 0.8557, 0.0000, 0.5231, 0.0000, 0.0000, 0.0000, 0.5369,
         0.6074],
        [0.9070, 0.6479, 0.7867, 0.0000, 0.0000, 0.5178, 0.8939, 0.8769, 0.0000,
         0.8086],
        [0.7964, 0.5915, 0.7268, 0.9707, 0.9202, 0.8453, 0.9848, 0.0000, 0.8562,
         0.0000],
        [0.0000, 0.0000, 0.0000, 0.7661, 0.8928, 0.0000, 0.5137, 0.5973, 0.0000,
         0.0000]])

#### 条件索引
1. tensor.nonzero()  
返回非零的值的索引  
2. 通过np.where()  

In [40]:
c = torch.arange(6).reshape(2,3)

In [47]:
# 返回符合条件的索引值，维度位置[1,2]-- 表示第0维的第1个，第1维的第二个
print((c > 2).nonzero())
c

tensor([[1, 0],
        [1, 1],
        [1, 2]])


tensor([[0, 1, 2],
        [3, 4, 5]])

In [49]:
import numpy as np

In [54]:
# 返回 两个向量来表示维度位置
d = c.numpy()
np.where(d>2)

(array([1, 1, 1], dtype=int64), array([0, 1, 2], dtype=int64))