### Tensor的基础运算都不会，那就是白学
加入广播机制的pytorch，如虎添翼
1. 四则运算 +(add),-(sub),*(mul),/(div)
2. 矩阵乘法 @(matmul)
3. 高级运算 -- 平方，开方，exp，log
4. 数值范围处理，及锁定 floor，ceil，round，clamp

In [3]:
import torch

In [4]:
a = torch.rand(4,4)
b = torch.rand(4)

In [5]:
a+b,torch.add(a,b)

(tensor([[1.0336, 0.7110, 1.1072, 1.2090],
         [0.9468, 0.6263, 1.1992, 1.0863],
         [0.8262, 0.6465, 1.4530, 0.8586],
         [1.1404, 0.9323, 1.5084, 1.2227]]),
 tensor([[1.0336, 0.7110, 1.1072, 1.2090],
         [0.9468, 0.6263, 1.1992, 1.0863],
         [0.8262, 0.6465, 1.4530, 0.8586],
         [1.1404, 0.9323, 1.5084, 1.2227]]))

In [6]:
a-b,torch.sub(a,b)

(tensor([[ 0.3672,  0.3144, -0.8748, -0.3119],
         [ 0.2804,  0.2297, -0.7828, -0.4346],
         [ 0.1598,  0.2499, -0.5290, -0.6623],
         [ 0.4739,  0.5357, -0.4736, -0.2982]]),
 tensor([[ 0.3672,  0.3144, -0.8748, -0.3119],
         [ 0.2804,  0.2297, -0.7828, -0.4346],
         [ 0.1598,  0.2499, -0.5290, -0.6623],
         [ 0.4739,  0.5357, -0.4736, -0.2982]]))

In [7]:
a*b,torch.mul(a,b)

(tensor([[0.2334, 0.1017, 0.1152, 0.3411],
         [0.2045, 0.0849, 0.2064, 0.2478],
         [0.1643, 0.0889, 0.4578, 0.0747],
         [0.2689, 0.1455, 0.5127, 0.3515]]),
 tensor([[0.2334, 0.1017, 0.1152, 0.3411],
         [0.2045, 0.0849, 0.2064, 0.2478],
         [0.1643, 0.0889, 0.4578, 0.0747],
         [0.2689, 0.1455, 0.5127, 0.3515]]))

In [8]:
a/b,torch.div(a,b)

(tensor([[2.1020, 2.5860, 0.1173, 0.5899],
         [1.8415, 2.1587, 0.2101, 0.4284],
         [1.4797, 2.2605, 0.4662, 0.1291],
         [2.4224, 3.7020, 0.5221, 0.6079]]),
 tensor([[2.1020, 2.5860, 0.1173, 0.5899],
         [1.8415, 2.1587, 0.2101, 0.4284],
         [1.4797, 2.2605, 0.4662, 0.1291],
         [2.4224, 3.7020, 0.5221, 0.6079]]))

In [9]:
c = torch.rand(4,3,28,32)
d = torch.rand(4,3,32,64)

In [10]:
# 注意是 @ 符号 
torch.all(torch.eq(torch.matmul(c,d),c@d))

tensor(1, dtype=torch.uint8)

In [12]:
c@d , torch.matmul(c,d)

(tensor([[[[ 8.2891,  8.4564,  8.6956,  ...,  9.8087,  8.9595,  9.1890],
           [ 8.4083,  7.6487,  8.8593,  ...,  8.9214,  8.9550,  9.0484],
           [ 7.4515,  6.5891,  7.8730,  ...,  8.5885,  7.9282,  9.8117],
           ...,
           [ 6.1918,  6.3913,  7.3255,  ...,  7.7384,  7.0346,  7.6230],
           [ 7.0444,  7.1097,  8.1652,  ...,  8.9674,  8.0266,  9.0355],
           [ 8.3042,  7.9419,  9.5316,  ...,  9.5271,  8.9178,  9.5394]],
 
          [[ 7.1395,  7.6126,  6.6021,  ...,  6.8944,  7.9205,  8.1801],
           [ 6.5939,  7.4271,  6.2355,  ...,  6.2770,  7.7297,  8.5909],
           [ 5.4864,  6.0416,  5.1060,  ...,  5.1131,  7.0953,  7.8028],
           ...,
           [ 5.2699,  5.7724,  5.7243,  ...,  5.2392,  6.9916,  7.3912],
           [ 6.2532,  6.5573,  5.9698,  ...,  6.7842,  7.8548,  7.3576],
           [ 6.9818,  8.6921,  7.1029,  ...,  8.4283,  9.2626,  9.2768]],
 
          [[ 6.9469,  7.4705,  9.1619,  ...,  7.2815,  9.1116,  8.6532],
           [ 

同理，就不一一展示  
pow(),是平方，也可以用 ** 2 表示  
sqrt（）,是平方根，也可以用 ** 0.5表示  
exp（） 表示指数函数  
log（），表示对数函数  
log2（），log10（） 是它的变形

#### 数值范围处理

In [14]:
e = torch.rand(1) * 10
e

tensor([8.2691])

In [19]:
# 下取值，上取值，四舍五入取值
torch.floor(e),torch.ceil(e),torch.round(e)

(tensor([8.]), tensor([9.]), tensor([8.]))

In [20]:
# 数值分解成 整数和小数  truncate and  fraction
torch.trunc(e), torch.frac(e)

(tensor([8.]), tensor([0.2691]))

In [22]:
# 设定上下限 clamp
f = torch.rand(3,3)*15
print(f)
f.clamp(5,10)

tensor([[ 3.6436,  1.6928,  1.5540],
        [ 0.9881,  0.2764,  8.7008],
        [12.9367,  9.8194, 11.9294]])


tensor([[ 5.0000,  5.0000,  5.0000],
        [ 5.0000,  5.0000,  8.7008],
        [10.0000,  9.8194, 10.0000]])

In [31]:
f.where(f>5,torch.tensor(5.))

tensor([[ 5.0000,  5.0000,  5.0000],
        [ 5.0000,  5.0000,  8.7008],
        [12.9367,  9.8194, 11.9294]])