### tensor的数据统计
1. 均值、总和、累乘
2. 最大最小，最大最小的对应参数
3. topk

__

torch.where 与 torch.gather 的使用

In [2]:
import torch

**基础统计**

In [14]:
A = torch.rand((10,2)) * 10
A

tensor([[8.7408, 6.6462],
        [8.8348, 2.1271],
        [3.9513, 8.0481],
        [7.9011, 5.3785],
        [1.5957, 1.4193],
        [0.1257, 8.9475],
        [3.3138, 1.5454],
        [1.5400, 7.7148],
        [1.9368, 8.7266],
        [9.4407, 7.2448]])

In [18]:
# 注意，tensor的类型要是 float
# ！这里遇到个问题，A是二维的，调用这些函数时，已经把A给拉成1维的再进行--需要注意
A.sum(), A.mean(), A.prod()

(tensor(105.1790), tensor(5.2589), tensor(2.6425e+11))

In [16]:
# 这个需要注意，与numpy的区别，numpy.max()返回的是 [max,argmax]
# 注意这个 18 ，是拉直后的坐标
A.max(), A.argmax(), A.min(), A.argmin()

(tensor(9.4407), tensor(18), tensor(0.1257), tensor(10))

In [24]:
A[:,1]

tensor([6.6462, 2.1271, 8.0481, 5.3785, 1.4193, 8.9475, 1.5454, 7.7148, 8.7266,
        7.2448])

In [25]:
A[:,1].max(), A[:,1].argmax(), A[:,1].min(), A[:,1].argmin()

(tensor(8.9475), tensor(5), tensor(1.4193), tensor(4))

#### Topk

In [37]:
# 这个就很好展现，A这个整体的比较值
# 常用于 Top-5 这样的验证算法中
_,indice = A[:,0].topk(3,0,sorted=True)
A[:,0].topk(3,0,sorted=True)

torch.return_types.topk(
values=tensor([9.4407, 8.8348, 8.7408]),
indices=tensor([9, 1, 0]))

In [44]:
# ！！ 惊了，索引居然可以直接载入tensor
A[indice]

tensor([[9.4407, 7.2448],
        [8.8348, 2.1271],
        [8.7408, 6.6462]])

#### 高阶操作
torch.where(conditon, A, B)  
条件判断

torch.gather(dict,dim,index)
字典查询
注意，字典的宽度要和索引的长度相匹配，即：  
dict -- Nx1  
index -- m  
则 dict = dict.expend(m,N)


In [48]:
A.where(A>5,torch.tensor(0.))

tensor([[8.7408, 6.6462],
        [8.8348, 0.0000],
        [0.0000, 8.0481],
        [7.9011, 5.3785],
        [0.0000, 0.0000],
        [0.0000, 8.9475],
        [0.0000, 0.0000],
        [0.0000, 7.7148],
        [0.0000, 8.7266],
        [9.4407, 7.2448]])

In [3]:
label = (torch.arange(10) + 10).expand(4,10)

In [4]:
label

tensor([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [14]:
idx = torch.randint(high=10,size=(4,2),dtype=torch.long)
idx

tensor([[9, 1],
        [3, 8],
        [9, 0],
        [6, 5]])

In [15]:
torch.gather(label,dim=1,index=idx)

tensor([[19, 11],
        [13, 18],
        [19, 10],
        [16, 15]])